[versions]
paper-api-current = "26.2.build.+"
paper-api-next = "26.3.build.+"

run-task = "3.1.0"
shadow = "9.6.1"

[libraries]
paper-api-current = { module = "io.papermc.paper:paper-api", version.ref = "paper-api-current" }
paper-api-next = { module = "io.papermc.paper:paper-api", version.ref = "paper-api-next" }

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
